# history-of-requests-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-of-requests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-of-requests
  template:
    metadata:
      labels:
        app: history-of-requests
    spec:
      containers:
      - name: history-of-requests
        image: history-of-requests:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: history-of-requests
spec:
  selector:
    app: history-of-requests
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer
