apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    path: /apis/metrics.k8s.io/v1beta1/nodes
    relabelConfigs:
    - sourceLabels: [__metrics_path__]
      action: replace
      targetLabel: metrics_path
      replacement: /apis/metrics.k8s.io/v1beta1/nodes