# request-processing-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-processing
  template:
    metadata:
      labels:
        app: request-processing
    spec:
      containers:
      - name: request-processing
        image: request-processing:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: request-processing
spec:
  selector:
    app: request-processing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
