# scoring-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoring
  template:
    metadata:
      labels:
        app: scoring
    spec:
      containers:
      - name: scoring
        image: scoring:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: scoring
spec:
  selector:
    app: scoring
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
