# security-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: security:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: security
spec:
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
