apiVersion: apps/v1
kind: Deployment
metadata:
  name: tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tests
  template:
    metadata:
      labels:
        app: tests
    spec:
      containers:
      - name: tests
        image: tests:latest
        imagePullPolicy: Never
        command: ["/bin/bash", "-c", "python -m pytest"]
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tests
spec:
  selector:
    app: tests
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
